<a href="https://colab.research.google.com/github/mamadoufoune6-spec/Data-sciencePortfolio/blob/main/Week1_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
hello github

In [ ]:
import numpy as np
#vectorized operations
a = np.array([1,2,3])
b = np.array ([4,5,6])
#arithmetic
print(a+b)
print(a-b)
print(a*b)
print(a/b)
#universal functions
print(np.sqrt(a))
print(np.exp(a))
print(np.cos(a))
#task find mean, median and std of a
print(np.mean(a))
print(np.median(a))
print(np.std(a))


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[ 0.54030231 -0.41614684 -0.9899925 ]
2.0
2.0
0.816496580927726


In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

#matrix multiplication
C = np.dot(A,B)
print(C)
#transpose
print(A.T)
#inverse square matrix
print(np.linalg.inv(A))

[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
 arr = np.array([10,20,30,40,50])
#indexing
print(arr[0])
print(arr[-1])
#Slicing
print(arr[1:4])
print(arr[:3])
print(arr[::2])
#Multi-dimensional arrays
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat[0,1])
print(mat[:,2])



10
50
[20 30 40]
[10 20 30]
[10 30 50]
2
[3 6 9]


In [ ]:
import numpy as np

  #create arrays
a = np.array([1,2,3,4])
b = np.array([[1,2],[3,4]])
#Array shape
print(a.shape)
print(b.shape)
#Basic operations
print(a*2)
print(a+2)
print(a+a)


(4,)
(2, 2)
[2 4 6 8]
[3 4 5 6]
[2 4 6 8]


In [57]:
# Mini project (simulate 1000 dice(1-6) rolls)
import numpy as np
# dice array
b = np.array([1,2,3,4,5,6])
a = np.random.choice(b, size=1000) # Use np.random.choice to simulate rolls
# mean, median, std, mode
print([np.mean(a)])
print([np.median(a)])
print([np.std(a)])
# extract rolls above 4
print([a[a>4]])
print(np.unique(a, return_counts=True)) # Removed the extra square brackets
# mode = np.argmax(np.bincount(a)) # This line was commented out in the user's original code, I will keep it commented out.
# print(mode)

[np.float64(3.38)]
[np.float64(3.0)]
[np.float64(1.71802211860034)]
[array([6, 6, 5, 6, 5, 5, 6, 6, 6, 5, 5, 6, 5, 6, 5, 5, 6, 6, 5, 5, 5, 5,
       5, 5, 5, 6, 6, 6, 5, 5, 5, 6, 5, 5, 5, 5, 6, 6, 6, 5, 5, 6, 6, 5,
       6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 5, 6, 6, 6, 5, 5, 5, 6, 6, 6, 5, 6,
       6, 6, 6, 6, 5, 6, 6, 6, 5, 6, 5, 6, 5, 6, 6, 5, 5, 6, 5, 5, 6, 5,
       5, 5, 6, 6, 5, 6, 5, 5, 6, 5, 5, 6, 6, 5, 6, 5, 5, 6, 6, 5, 6, 5,
       5, 6, 5, 6, 5, 6, 5, 6, 6, 6, 5, 5, 6, 5, 6, 5, 6, 6, 6, 6, 5, 5,
       5, 5, 6, 6, 5, 5, 6, 5, 5, 6, 6, 5, 5, 5, 5, 5, 6, 6, 6, 5, 6, 6,
       5, 5, 5, 6, 6, 5, 5, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 5,
       6, 6, 6, 6, 5, 5, 5, 6, 5, 6, 5, 5, 5, 6, 6, 6, 5, 5, 6, 6, 6, 6,
       6, 5, 5, 5, 5, 6, 5, 6, 6, 6, 6, 6, 5, 6, 6, 5, 6, 5, 5, 5, 6, 5,
       6, 6, 6, 5, 6, 6, 5, 5, 6, 6, 6, 5, 6, 5, 6, 6, 6, 5, 5, 6, 5, 6,
       6, 5, 6, 5, 5, 5, 6, 5, 6, 6, 5, 6, 5, 6, 6, 6, 6, 5, 6, 6, 5, 6,
       5, 6, 6, 5, 6, 5, 6, 6, 5, 5, 6, 6, 6, 5, 5, 6, 

In [58]:
# Mini project (simulate 1000 dice(1-6) rolls)
import numpy as np
# dice array
b = np.array([1,2,3,4,5,6])
a = np.random.choice(b, size=1000) # Use np.random.choice to simulate rolls
# mean, median, std, mode
print(f"Mean: {np.mean(a)}")
print(f"Median: {np.median(a)}")
print(f"Standard deviation: {np.std(a)}")
# extract rolls above 4
print(f"Rolls above 4: {a[a>4]}")
print(f"Unique values and counts: {np.unique(a, return_counts=True)}")
mode = np.argmax(np.bincount(a))
print(f"Mode: {mode}")

Mean: 3.41
Median: 3.0
Standard deviation: 1.671496335622666
Rolls above 4: [6 5 6 6 5 6 6 6 6 5 5 5 5 5 6 5 6 6 5 5 6 5 5 5 5 5 5 6 6 5 5 5 6 6 6 6 5
 5 5 6 5 5 5 6 6 6 5 5 6 6 6 5 5 5 5 5 6 5 5 5 6 5 6 6 6 6 6 5 6 5 6 5 6 5
 6 6 5 6 6 6 6 5 5 6 5 5 5 5 5 6 5 6 6 5 5 6 6 5 6 5 6 5 6 6 6 5 5 6 6 6 6
 6 5 6 5 6 6 5 6 5 5 6 6 5 6 6 5 5 5 5 5 5 6 5 5 6 5 6 6 6 5 6 6 6 5 5 5 6
 5 5 5 5 5 5 5 5 6 5 6 6 5 5 6 6 5 5 5 6 5 6 6 6 6 5 5 5 6 6 5 5 6 6 5 6 5
 6 5 6 6 6 5 5 5 6 6 5 6 6 5 6 6 6 5 6 5 6 5 5 6 5 6 6 6 5 6 6 6 6 5 6 6 6
 5 5 5 5 6 6 6 6 6 6 5 5 5 6 5 5 6 6 6 5 6 6 5 5 6 5 6 5 6 5 5 5 5 5 6 5 6
 6 5 5 5 5 5 5 5 6 5 6 6 5 6 5 5 6 5 5 6 6 5 6 6 5 5 5 5 6 6 6 5 5 5 5 5 5
 5 6 6 6 6 5 5 5]
Unique values and counts: (array([1, 2, 3, 4, 5, 6]), array([165, 185, 175, 171, 158, 146]))
Mode: 2
